spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jaegoo?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 3579

mybatis:
  mapper-locations: classpath:mapper/**.xml
